trigger:
  name: Update changelog on PR merge
  identifier: update_changelog_on_merge
  enabled: true
  orgIdentifier: PROD
  projectIdentifier: Harness_Commons
  pipelineIdentifier: update_changelog
  source:
    type: Webhook
    spec:
      type: Harness
      spec:
        type: PullRequest
        spec:
          repoName: canary
          actions:
            - Merge
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
  inputYaml: |
    pipeline:
      identifier: update_changelog
      properties:
        ci:
          codebase:
            build:
              type: branch
              spec:
                branch: main
