export enum FeatureFlag {
  SEMANTIC_SEARCH_ENABLED = 'SEMANTIC_SEARCH_ENABLED',
  CODE_SSH_ENABLED = 'CODE_SSH_ENABLED',
  CODE_SECURITY_SCANNING_ON_PUSH = 'CODE_SECURITY_SCANNING_ON_PUSH',
  CODE_FORK_ENABLED = 'CODE_FORK_ENABLED'
}
