import { IconV2NamesType } from '@components/icon-v2'
import { LogoNameMapV2 } from '@components/logo-v2'

import { ConnectorConfigType } from '../types'

export const ConnectorTypeToLogoNameMap: Map<ConnectorConfigType, keyof typeof LogoNameMapV2> = new Map([
  ['Github', 'github'],
  ['Gitlab', 'gitlab'],
  ['Bitbucket', 'bitbucket'],
  ['Jira', 'jira'],
  ['K8sCluster', 'kubernetes'],
  ['DockerRegistry', 'docker'],
  ['Aws', 'aws'],
  ['AwsSecretManager', 'aws'],
  ['Gcp', 'google'],
  ['GcpSecretManager', 'google'],
  ['GcpKms', 'google'],
  ['AwsKms', 'aws'],
  ['TerraformCloud', 'terraform'],
  ['Terraform', 'terraform'],
  ['Vault', 'hashicorp'],
  ['HttpHelmRepo', 'helm'],
  ['Rancher', 'rancher'],
  ['Datadog', 'data-dog'],
  ['ServiceNow', 'servicenow'],
  ['SignalFX', 'sfx'],
  ['NewRelic', 'new-relic'],
  ['Git', 'git'],
  ['Splunk', 'splunk'],
  ['Prometheus', 'prometheus'],
  ['Dynatrace', 'dynatrace'],
  ['Nexus', 'nexus'],
  ['AppDynamics', 'app-dynamics'],
  ['ElasticSearch', 'elastic'],
  ['AzureKeyVault', 'azure'],
  ['Azure', 'azure'],
  ['AzureRepo', 'azure'],
  ['Artifactory', 'artifactory'],
  ['OciHelmRepo', 'helm'],
  ['Tas', 'tanzu'],
  ['AzureArtifacts', 'azure'],
  ['Jenkins', 'jenkins'],
  ['Bamboo', 'bamboo'],
  ['Spot', 'spot'],
  ['PagerDuty', 'pagerduty'],
  ['JDBC', 'java'],
  ['SumoLogic', 'sumo-logic'],
  ['Slack', 'slack'],
  ['Zoom', 'zoom'],
  ['MsTeams', 'ms-teams'],
  ['Confluence', 'confluence']
])

export const ConnectorTypeToIconNameMap: Map<ConnectorConfigType, IconV2NamesType> = new Map([
  ['Pdc', 'physical-data-center'],
  ['CustomHealth', 'health-shield']
  // ['ErrorTracking', 'error-tracking']
])

export const ConnectorDisplayNameMap: Map<ConnectorConfigType, string> = new Map([
  ['K8sCluster', 'Kubernetes cluster'],
  ['Git', 'Git'],
  ['Github', 'GitHub'],
  ['Gitlab', 'GitLab'],
  ['Bitbucket', 'Bitbucket'],
  ['AzureRepo', 'Azure Repos'],
  ['DockerRegistry', 'Docker Registry'],
  ['Gcp', 'GCP - Cloud Provider'],
  ['Pdc', 'Physical Data Center'],
  ['AppDynamics', 'AppDynamics'],
  ['Splunk', 'Splunk'],
  ['NewRelic', 'New Relic'],
  ['Prometheus', 'Prometheus'],
  ['Aws', 'AWS - Cloud Provider'],
  ['Codecommit', 'AWS CodeCommit'],
  ['Nexus', 'Nexus'],
  ['Local', 'Local Secret Manager'],
  ['Vault', 'HashiCorp Vault'],
  ['GcpKms', 'GCP KMS'],
  ['AzureKeyVault', 'Azure Vault'],
  ['HttpHelmRepo', 'HTTP Helm Repo'],
  ['OciHelmRepo', 'OCI Helm Registry'],
  ['AwsSecretManager', 'AWS Secrets Manager'],
  ['AwsKms', 'AWS KMS'],
  ['AzureKeyVault', 'Azure Key Vault'],
  ['Dynatrace', 'Dynatrace'],
  ['CEAws', 'AWS - Cloud Cost'],
  ['CEAzure', 'Azure - Cloud Cost'],
  ['CEK8sCluster', 'Kubernetes'],
  ['GcpCloudCost', 'GCP - Cloud Cost'],
  ['Azure', 'Azure - Cloud Provider'],
  ['ErrorTracking', 'Error Tracking'],
  ['CustomSecretManager', 'Custom Secrets Manager'],
  ['GcpSecretManager', 'GCP Secrets Manager'],
  ['Spot', 'Spot'],
  ['AzureArtifacts', 'Azure Artifacts'],
  ['Tas', 'Tanzu Application Service'],
  ['TerraformCloud', 'Terraform Cloud'],
  ['SignalFX', 'Splunk Observability [SignalFX]'],
  ['Rancher', 'Rancher cluster'],
  ['Zoom', 'Zoom'],
  ['MsTeams', 'Microsoft Teams'],
  ['Slack', 'Slack'],
  ['Confluence', 'Confluence'],
  ['Datadog', 'Datadog'],
  ['SumoLogic', 'Sumo Logic'],
  ['Artifactory', 'Artifactory'],
  ['Jira', 'Jira'],
  ['ServiceNow', 'ServiceNow'],
  ['CustomHealth', 'Custom Health'],
  ['JDBC', 'JDBC'],
  ['Jenkins', 'Jenkins'],
  ['PagerDuty', 'OpsGenie']
])
