import {
  Breadcrumb,
  Button,
  IconV2,
  Layout,
  SearchInput,
  Separator,
  Text
} from '@harnessio/ui/components'
import { SandboxLayout } from '@harnessio/views'
import type { ReactNode } from 'react'

/**
 * FME → Feature Flag List — shared page chrome.
 *
 * One module, imported by all three artboard prototypes (empty / list / create
 * drawer) so the page header, breadcrumb, title row, and filter toolbar are
 * BYTE-IDENTICAL across screens. This is deliberate: the cross-screen synthesis
 * pass should judge real consistency signal (token drift, empty-state treatment),
 * not noise introduced by three generators reinventing the same header.
 *
 * Generated by designAI's /design-prototype multi-frame workflow from the Figma
 * Section "Feature flag list" (node 2156:65214, file MUFBhLa9rquSdNTT1eGbfZ),
 * grounded in the Canary component manifest + the usage briefs, verified clean
 * against the manifest before landing here.
 *
 * Scope: reproduces the page-container content of each frame — the global
 * Sidebar (256px) and the AI-chat panel (412px) are existing shell chrome, not
 * part of this node's design intent (same scope call as the fme-overview run).
 */

/** Location row: chrome toggles + breadcrumb. Identical across all three frames. */
export function FlagListLocationRow(): JSX.Element {
  return (
    <Layout.Horizontal gap="2xs" align="center">
      <Button
        variant="ghost"
        size="sm"
        iconOnly
        tooltipProps={{ content: 'Toggle AI chat' }}
      >
        <IconV2 name="chat-bubble" />
      </Button>
      <Button
        variant="ghost"
        size="sm"
        iconOnly
        tooltipProps={{ content: 'Toggle panel' }}
      >
        <IconV2 name="expand-sidebar" />
      </Button>
      {/* Separator keeps chrome toggles from blurring into the location trail
          (fme-overview critique flagged the missing gap; fixed here). */}
      <Separator orientation="vertical" className="mx-cn-xs h-cn-md" />
      <Breadcrumb.Root>
        <Breadcrumb.List>
          <Breadcrumb.Item>
            <Breadcrumb.Link href="/fme">Feature Rollout</Breadcrumb.Link>
          </Breadcrumb.Item>
          <Breadcrumb.Separator />
          <Breadcrumb.Item>
            <Breadcrumb.Page>Feature Flags</Breadcrumb.Page>
          </Breadcrumb.Item>
        </Breadcrumb.List>
      </Breadcrumb.Root>
    </Layout.Horizontal>
  )
}

/**
 * Title row: page heading + the "New Feature Flag" action.
 *
 * `createVariant` lets a frame demote this button to `outline` so a view never
 * shows two filled primaries (→ *hierarchy earns attention*). The empty/first-run
 * frame demotes it because its in-body NoData carries the single filled CTA; the
 * populated + create frames keep it filled (it's their only primary).
 */
export function FlagListTitleRow({
  onCreate,
  createVariant = 'primary'
}: {
  onCreate?: () => void
  createVariant?: 'primary' | 'outline'
}): JSX.Element {
  return (
    <Layout.Horizontal justify="between" align="center">
      <Text variant="heading-subsection" as="h1" color="foreground-1">
        Feature Flags
      </Text>
      <Button variant={createVariant} size="md" onClick={onCreate}>
        <IconV2 name="plus" />
        New Feature Flag
      </Button>
    </Layout.Horizontal>
  )
}

/**
 * Filter toolbar: search + saved-view + pin + add-filter.
 * Identical across the empty and populated frames (the create-drawer frame
 * renders it underneath the open drawer).
 */
export function FlagListToolbar(): JSX.Element {
  return (
    <Layout.Horizontal gap="sm" align="center">
      <SearchInput
        placeholder="Search feature flag name"
        inputContainerClassName="w-[360px]"
      />
      <Button variant="outline" size="md">
        <IconV2 name="account" />
        My feature flags
      </Button>
      <Button
        variant="ghost"
        size="md"
        iconOnly
        tooltipProps={{ content: 'Pin this view' }}
      >
        <IconV2 name="pin" />
      </Button>
      <Button variant="ghost" size="md">
        <IconV2 name="plus" />
        Add filter
      </Button>
    </Layout.Horizontal>
  )
}

/**
 * The page shell every frame shares: SandboxLayout container + location row +
 * title row + the page body each frame supplies as children. The toolbar is
 * passed in (the create frame still shows it, but it sits under the drawer).
 */
export function FlagListPage({
  onCreate,
  createVariant = 'primary',
  children
}: {
  onCreate?: () => void
  createVariant?: 'primary' | 'outline'
  children: ReactNode
}): JSX.Element {
  return (
    <SandboxLayout.Main>
      <SandboxLayout.Content className="py-cn-xl">
        <Layout.Vertical gap="lg">
          <FlagListLocationRow />
          <FlagListTitleRow onCreate={onCreate} createVariant={createVariant} />
          <FlagListToolbar />
          {children}
        </Layout.Vertical>
      </SandboxLayout.Content>
    </SandboxLayout.Main>
  )
}
