import { useState } from 'react'
import {
  Button,
  Card,
  CounterBadge,
  IconV2,
  Layout,
  Progress,
  Separator,
  StackedList,
  StatusBadge,
  Tabs,
  Tag,
  Text
} from '@harnessio/ui/components'
import { SandboxLayout } from '@harnessio/views'

/**
 * Deploy Health — a service-deploy dashboard panel.
 *
 * Prototype generated by designAI's /design-prototype from the intent
 * "a deploy-health dashboard panel for a service: live rollout, recent
 * deploys, environment status", grounded in the Canary component manifest
 * (160 components) + usage briefs for Card / Button / StatusBadge / Layout /
 * Text, and verified clean against the manifest before landing here.
 *
 * Why this exists: it's the layer-one artifact for the AI-prototyping story —
 * proof that an AI-generated prototype composes REAL @harnessio/ui components
 * (not divs + Tailwind), passes the mechanical manifest gate, and renders
 * standalone with zero backend. The data below is static fixture data; no
 * harness-core-ui shell, routing, auth, or service is booted to show this.
 *
 * Default export + real imports follow the view-preview subject pattern and
 * is auto-discovered by view-preview.tsx via import.meta.glob — no registry edit.
 */

type DeployState = 'success' | 'failed' | 'running' | 'pending'

type Deploy = {
  id: string
  version: string
  env: 'production' | 'staging' | 'qa'
  author: string
  branch: string
  when: string
  state: DeployState
}

const DEPLOYS: Deploy[] = [
  { id: 'd-4821', version: 'v2.14.3', env: 'production', author: 'a.rao', branch: 'release/2.14', when: '4m ago', state: 'running' },
  { id: 'd-4820', version: 'v2.14.2', env: 'production', author: 'j.hawkins', branch: 'release/2.14', when: '2h ago', state: 'success' },
  { id: 'd-4818', version: 'v2.14.2', env: 'staging', author: 'm.lee', branch: 'main', when: '5h ago', state: 'success' },
  { id: 'd-4814', version: 'v2.14.1', env: 'production', author: 'p.shah', branch: 'release/2.14', when: 'yesterday', state: 'failed' },
  { id: 'd-4809', version: 'v2.14.0', env: 'qa', author: 'a.rao', branch: 'main', when: 'yesterday', state: 'success' }
]

const ENVIRONMENTS: { name: string; region: string; state: DeployState; version: string }[] = [
  { name: 'production', region: 'us-east-1', state: 'running', version: 'v2.14.3' },
  { name: 'staging', region: 'us-east-1', state: 'success', version: 'v2.14.2' },
  { name: 'qa', region: 'eu-west-1', state: 'success', version: 'v2.14.0' }
]

// StatusBadge brief: pair an icon with the theme so meaning survives without
// color (→ "Color is never the only signal"). For live/in-progress use
// variant="status" + pulse (animated dot) — and the brief forbids `icon` there,
// since the dot does the work. Terminal states use a static variant + icon.
function badgeFor(state: DeployState) {
  switch (state) {
    case 'success':
      return { variant: 'secondary' as const, theme: 'success' as const, icon: 'check-circle' as const, pulse: false, label: 'Succeeded' }
    case 'failed':
      return { variant: 'secondary' as const, theme: 'danger' as const, icon: 'xmark-circle' as const, pulse: false, label: 'Failed' }
    case 'running':
      return { variant: 'status' as const, theme: 'info' as const, icon: undefined, pulse: true, label: 'Rolling out' }
    case 'pending':
      return { variant: 'secondary' as const, theme: 'warning' as const, icon: 'clock' as const, pulse: false, label: 'Pending' }
  }
}

export default function DeployHealth(): JSX.Element {
  const [tab, setTab] = useState<string>('deploys')

  return (
    <SandboxLayout.Root>
      <SandboxLayout.Content className="p-cn-xl">
        <Layout.Vertical gap="xl">
          {/* Header */}
          <Layout.Horizontal gap="md" className="items-center justify-between">
            <Layout.Vertical gap="2xs">
              <Layout.Horizontal gap="sm" className="items-center">
                <Text variant="heading-section">Deploy Health</Text>
                <StatusBadge variant="status" theme="info" pulse>
                  Live rollout
                </StatusBadge>
              </Layout.Horizontal>
              <Text variant="body-normal" color="foreground-3">
                payments-service · release/2.14
              </Text>
            </Layout.Vertical>
            <Layout.Horizontal gap="sm" className="items-center">
              <Button variant="outline" size="sm">
                <IconV2 name="refresh" size="xs" />
                Refresh
              </Button>
              <Button variant="primary" size="sm">
                <IconV2 name="play" size="xs" />
                New deploy
              </Button>
            </Layout.Horizontal>
          </Layout.Horizontal>

          {/* Live rollout summary card */}
          <Card.Root>
            <Card.Content className="p-cn-lg">
              <Layout.Vertical gap="md">
                <Layout.Horizontal gap="md" className="items-center justify-between">
                  <Layout.Horizontal gap="sm" className="items-center">
                    <IconV2 name="git-branch" size="sm" color="info" />
                    <Text variant="body-strong">v2.14.3 → production</Text>
                    <Tag variant="secondary" theme="blue" size="sm" value="us-east-1" />
                  </Layout.Horizontal>
                  <Text variant="caption-normal" color="foreground-3">
                    started 4m ago · a.rao
                  </Text>
                </Layout.Horizontal>
                {/* Honest status — show real progress while propagating, not a */}
                {/* premature success. `value` is a 0–1 fraction; `color` and */}
                {/* `state` are mutually exclusive, so pick `color` here. */}
                <Progress value={0.62} color="blue" size="md" />
                <Layout.Horizontal gap="lg">
                  <Layout.Vertical gap="3xs">
                    <Text variant="caption-light" color="foreground-3">Healthy pods</Text>
                    <Text variant="body-strong">38 / 60</Text>
                  </Layout.Vertical>
                  <Layout.Vertical gap="3xs">
                    <Text variant="caption-light" color="foreground-3">Error rate</Text>
                    <Text variant="body-strong" color="success">0.02%</Text>
                  </Layout.Vertical>
                  <Layout.Vertical gap="3xs">
                    <Text variant="caption-light" color="foreground-3">p95 latency</Text>
                    <Text variant="body-strong">214ms</Text>
                  </Layout.Vertical>
                </Layout.Horizontal>
              </Layout.Vertical>
            </Card.Content>
          </Card.Root>

          {/* Tabs: recent deploys / environments */}
          <Tabs.Root value={tab} onValueChange={setTab}>
            <Tabs.List>
              <Tabs.Trigger value="deploys">
                Recent deploys
                <CounterBadge variant="secondary" theme="default">
                  {DEPLOYS.length}
                </CounterBadge>
              </Tabs.Trigger>
              <Tabs.Trigger value="environments">
                Environments
                <CounterBadge variant="secondary" theme="default">
                  {ENVIRONMENTS.length}
                </CounterBadge>
              </Tabs.Trigger>
            </Tabs.List>

            <Tabs.Content value="deploys">
              <StackedList.Root>
                <StackedList.Header>
                  <StackedList.Field title="Deploy" />
                  <StackedList.Field title="Environment" />
                  <StackedList.Field title="Status" />
                </StackedList.Header>
                {DEPLOYS.map((d) => {
                  const b = badgeFor(d.state)
                  return (
                    <StackedList.Item key={d.id}>
                      <StackedList.Field
                        title={`${d.version} · ${d.id}`}
                        description={`${d.branch} · ${d.author} · ${d.when}`}
                      />
                      <StackedList.Field
                        title={<Tag variant="outline" theme="gray" size="sm" value={d.env} />}
                      />
                      <StackedList.Field
                        title={
                          <StatusBadge variant={b.variant} theme={b.theme} icon={b.icon} pulse={b.pulse}>
                            {b.label}
                          </StatusBadge>
                        }
                      />
                    </StackedList.Item>
                  )
                })}
              </StackedList.Root>
            </Tabs.Content>

            <Tabs.Content value="environments">
              <Layout.Grid gap="md" className="grid-cols-3">
                {ENVIRONMENTS.map((e) => {
                  const b = badgeFor(e.state)
                  return (
                    <Card.Root key={e.name}>
                      <Card.Content className="p-cn-md">
                        <Layout.Vertical gap="sm">
                          <Layout.Horizontal gap="sm" className="items-center justify-between">
                            <Text variant="body-strong" className="capitalize">{e.name}</Text>
                            <StatusBadge variant={b.variant} theme={b.theme} icon={b.icon} pulse={b.pulse} size="sm">
                              {b.label}
                            </StatusBadge>
                          </Layout.Horizontal>
                          <Separator />
                          <Layout.Horizontal gap="sm" className="items-center">
                            <IconV2 name="timer" size="xs" color="merged" />
                            <Text variant="caption-normal" color="foreground-3">
                              {e.version} · {e.region}
                            </Text>
                          </Layout.Horizontal>
                        </Layout.Vertical>
                      </Card.Content>
                    </Card.Root>
                  )
                })}
              </Layout.Grid>
            </Tabs.Content>
          </Tabs.Root>
        </Layout.Vertical>
      </SandboxLayout.Content>
    </SandboxLayout.Root>
  )
}
