import { Layout, Link, NoData, Text } from '@harnessio/ui/components'
import { SandboxLayout } from '@harnessio/views'

/**
 * Empty-repository first-run state.
 *
 * Prototype generated by designAI's /design-prototype, grounded in the Canary
 * component manifest + the NoData usage brief (first-run gets a primaryButton
 * that creates the first item — "no dead ends"), and verified clean against the
 * manifest before landing here. Default export + real imports follow the
 * view-preview subject pattern (subjects/views/data-table-demo.tsx).
 *
 * Auto-discovered by view-preview.tsx via import.meta.glob — no registry edit.
 */
export default function EmptyRepoPrototype(): JSX.Element {
  return (
    <SandboxLayout.Main>
      <SandboxLayout.Content>
        <Layout.Vertical gap="md" align="center" className="mt-cn-3xl">
          <Text variant="heading-section">Repositories</Text>
          <NoData
            imageName="no-data-cog"
            title="Create your first repository"
            description={[
              'Repositories store your code and track its history.',
              'Import an existing project or start one from scratch.'
            ]}
            primaryButton={{
              label: 'Create repository',
              icon: 'plus',
              onClick: () => {}
            }}
            secondaryButton={{
              label: 'Import repository',
              icon: 'download',
              onClick: () => {}
            }}
          />
          <Link to="/docs" size="sm">
            View documentation
          </Link>
        </Layout.Vertical>
      </SandboxLayout.Content>
    </SandboxLayout.Main>
  )
}
