import {
  Accordion,
  Avatar,
  Breadcrumb,
  Button,
  Card,
  IconV2,
  Layout,
  Link,
  PromptInput,
  Sidebar,
  Table,
  Tag,
  Text
} from '@harnessio/ui/components'
import { SandboxLayout } from '@harnessio/views'

/**
 * FME → Overview, full app-shell.
 *
 * Prototype generated by designAI's /design-prototype from the Figma frame
 * "app-shell" (FME, node 5741:273028), light mode, grounded in the Canary
 * component manifest + usage briefs for Sidebar / Chat / Breadcrumb / Card /
 * Accordion / Table / Tag / Button, and verified clean against the manifest.
 *
 * Three zones, matching the frame: a 256px global Sidebar (FME nav) · a 412px
 * AI-chat panel · the Overview page body. The Overview body is the prior
 * page-only prototype, kept intact. The frame has NO global top header — the
 * breadcrumb lives in the page-top-nav inside the main column — so this
 * hand-rolls the three-zone grid rather than using the blessed `SidebarLayout`
 * (which draws its own Header and would double the chrome). Custom layout via
 * `cn-`/grid utilities; every visual is a real `@harnessio/ui` component.
 *
 * Default export + real imports follow the view-preview subject pattern; it's
 * auto-discovered by view-preview.tsx via import.meta.glob — no registry edit.
 */

/* ────────────────────────────────────────────────────────────────────────
 * Zone 1 — Global sidebar (FME nav)
 * ──────────────────────────────────────────────────────────────────────── */

type NavItem = { icon: string; title: string; to: string }

const featureRolloutItems: NavItem[] = [
  { icon: 'dashboard', title: 'Overview', to: '/fme/overview' },
  { icon: 'environments', title: 'Environments', to: '/fme/environments' },
  { icon: 'view-grid', title: 'Rollout Board', to: '/fme/rollout-board' },
  { icon: 'pipeline', title: 'Pipelines', to: '/fme/pipelines' },
  { icon: 'flag-solid', title: 'Flags', to: '/fme/flags' },
  { icon: 'ai-test', title: 'Experiments', to: '/fme/experiments' },
  { icon: 'group-1', title: 'Segments', to: '/fme/segments' },
  { icon: 'stats-report', title: 'Metrics', to: '/fme/metrics' },
  { icon: 'databases-solid', title: 'Data Hub', to: '/fme/data-hub' },
  { icon: 'sparks-solid', title: 'Ask Release Agent', to: '/fme/agent' },
  { icon: 'settings', title: 'Settings', to: '/fme/settings' }
]

const ACTIVE_PATH = '/fme/overview'

function AppNav(): JSX.Element {
  return (
    // cn-content-full-height sizes the rail to the viewport so it doesn't spill
    // past the bottom edge — matches the real SideNav.
    <Sidebar.Root className="cn-content-full-height">
      <Sidebar.Header>
        <Layout.Horizontal gap="xs" align="center" className="px-cn-2xs py-cn-xs">
          <Avatar name="Harness" size="md" rounded />
          <Layout.Vertical gap="none">
            <Text variant="body-single-line-strong" color="foreground-1">
              Harness
            </Text>
            <Text variant="caption-single-line-normal" color="foreground-3">
              default
            </Text>
          </Layout.Vertical>
        </Layout.Horizontal>
      </Sidebar.Header>

      <Sidebar.Content>
        <Sidebar.Group>
          <Sidebar.Item icon="dashboard-solid" title="Home" to="/home" />
          <Sidebar.Item icon="sparks-solid" title="Activity" to="/activity" />
          <Sidebar.Item icon="more-horizontal" title="more" to="/more" />
        </Sidebar.Group>

        <Sidebar.Group label="Recent">
          <Sidebar.Item
            icon="feature-flags"
            title="Feature Rollout"
            to="/fme"
            defaultSubmenuOpen
          >
            {featureRolloutItems.map(item => (
              <Sidebar.MenuSubItem
                key={item.to}
                title={item.title}
                to={item.to}
                active={item.to === ACTIVE_PATH}
              />
            ))}
          </Sidebar.Item>
        </Sidebar.Group>
      </Sidebar.Content>

      <Sidebar.Footer>
        <Layout.Horizontal gap="xs" align="center" className="px-cn-2xs py-cn-xs">
          <Avatar name="Bradley Rydzewski" size="sm" />
          <Text variant="body-single-line-normal" color="foreground-2">
            bradley-rydzewski
          </Text>
        </Layout.Horizontal>
      </Sidebar.Footer>
    </Sidebar.Root>
  )
}

/* ────────────────────────────────────────────────────────────────────────
 * Zone 2 — AI-chat panel
 * ──────────────────────────────────────────────────────────────────────── */

function ChatPanel(): JSX.Element {
  return (
    <Layout.Vertical
      className="cn-content-full-height border-r"
      style={{ width: 412 }}
    >
      {/* Panel header — title + per-panel actions (the frame's icon row) */}
      <Layout.Horizontal
        justify="between"
        align="center"
        className="px-cn-lg py-cn-md"
      >
        <Text variant="heading-small" as="h2" color="foreground-1">
          Title
        </Text>
        <Layout.Horizontal gap="2xs" align="center">
          <Button variant="ghost" size="sm" iconOnly tooltipProps={{ content: 'New chat' }}>
            <IconV2 name="edit-pencil" />
          </Button>
          <Button variant="ghost" size="sm" iconOnly tooltipProps={{ content: 'Split view' }}>
            <IconV2 name="split-view" />
          </Button>
          <Button variant="ghost" size="sm" iconOnly tooltipProps={{ content: 'More' }}>
            <IconV2 name="more-horizontal" />
          </Button>
        </Layout.Horizontal>
      </Layout.Horizontal>

      {/* Empty thread — a starting affordance, not a blank panel (→ no dead ends) */}
      <Layout.Vertical className="flex-1 overflow-y-auto px-cn-lg" />

      {/* Composer — real PromptInput: textarea + tools + submit */}
      <Layout.Vertical className="px-cn-lg py-cn-md">
        <PromptInput.Root
          onSubmit={e => e.preventDefault()}
          className="border-cn-2 rounded-cn-5 border p-cn-sm"
        >
          <PromptInput.Textarea placeholder="Ask Harness..." autoResize />
          <PromptInput.Toolbar className="mt-cn-xs">
            <PromptInput.Tools>
              <PromptInput.Button aria-label="Attach">
                <IconV2 name="plus" />
              </PromptInput.Button>
              <PromptInput.Button aria-label="Add context">
                <IconV2 name="attachment" />
              </PromptInput.Button>
            </PromptInput.Tools>
            <Layout.Horizontal gap="2xs" align="center">
              <Button variant="ghost" size="xs">
                Sonnet 4.6
                <IconV2 name="nav-arrow-down" size="2xs" />
              </Button>
              <PromptInput.Submit aria-label="Send" />
            </Layout.Horizontal>
          </PromptInput.Toolbar>
        </PromptInput.Root>
      </Layout.Vertical>
    </Layout.Vertical>
  )
}

/* ────────────────────────────────────────────────────────────────────────
 * Zone 3 — Overview page body (carried over from the page-only prototype)
 * ──────────────────────────────────────────────────────────────────────── */

type Principal = {
  name: string
  isGroup?: boolean
}

type ApprovalRow = {
  id: string
  type: 'Segment' | 'Feature Flag'
  name: string
  time: string
  /** the owners of the resource */
  owners: Principal[]
  /** approvals view only: who submitted the request */
  submitter?: Principal
  /** submissions view only: who will approve the request */
  approvers?: Principal[]
}

const outstandingApprovals: ApprovalRow[] = [
  {
    id: 'a1',
    type: 'Segment',
    name: 'customer_support',
    time: '2d ago',
    owners: [{ name: 'dave.karow' }, { name: 'All FME Admins', isGroup: true }],
    submitter: { name: 'jared.hawkins' }
  },
  {
    id: 'a2',
    type: 'Feature Flag',
    name: 'database_write_freeze_data',
    time: '1d ago',
    owners: [{ name: 'All FME Admins', isGroup: true }],
    submitter: { name: 'ivan.delagarzatamez' }
  },
  {
    id: 'a3',
    type: 'Segment',
    name: 'designers',
    time: '3d ago',
    owners: [{ name: 'jared hawkins' }],
    submitter: { name: 'brentt.smith' }
  }
]

const outstandingSubmissions: ApprovalRow[] = [
  {
    id: 's1',
    type: 'Segment',
    name: 'customer_support',
    time: '4d ago',
    owners: [{ name: 'dave.karow' }, { name: 'All FME Admins', isGroup: true }],
    approvers: [{ name: 'jared.hawkins' }]
  }
]

function PrincipalTag({ principal }: { principal: Principal }): JSX.Element {
  return (
    <Tag
      variant="secondary"
      theme="gray"
      size="md"
      icon={principal.isGroup ? 'group-1' : 'account-solid'}
      value={principal.name}
    />
  )
}

function PrincipalCell({ principals }: { principals: Principal[] }): JSX.Element {
  return (
    <Layout.Horizontal gap="2xs" wrap="wrap" align="center">
      {principals.map(p => (
        <PrincipalTag key={p.name} principal={p} />
      ))}
    </Layout.Horizontal>
  )
}

/** Approvals: Type · Name · Time · Owner · Submitter · (View) */
function ApprovalsTable({ rows }: { rows: ApprovalRow[] }): JSX.Element {
  return (
    <Table.Root size="compact">
      <Table.Header>
        <Table.Row>
          <Table.Head>Type</Table.Head>
          <Table.Head>Name</Table.Head>
          <Table.Head>Time</Table.Head>
          <Table.Head>Owner</Table.Head>
          <Table.Head>Submitter</Table.Head>
          <Table.Head>
            <span className="sr-only">Actions</span>
          </Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {rows.map(row => (
          <Table.Row key={row.id}>
            <Table.Cell>
              <Text variant="body-single-line-normal" color="foreground-2">
                {row.type}
              </Text>
            </Table.Cell>
            <Table.Cell className="font-medium">{row.name}</Table.Cell>
            <Table.Cell>
              <Text variant="caption-single-line-normal" color="foreground-3">
                {row.time}
              </Text>
            </Table.Cell>
            <Table.Cell>
              <PrincipalCell principals={row.owners} />
            </Table.Cell>
            <Table.Cell>
              {row.submitter ? <PrincipalTag principal={row.submitter} /> : null}
            </Table.Cell>
            <Table.Cell className="text-right">
              <Button variant="outline" size="xs" asChild>
                <Link to={`/fme/requests/${row.id}`} noHoverUnderline>
                  View
                </Link>
              </Button>
            </Table.Cell>
          </Table.Row>
        ))}
      </Table.Body>
    </Table.Root>
  )
}

/** Submissions: Type · Name · Time · Owner · Approvers · (View) */
function SubmissionsTable({ rows }: { rows: ApprovalRow[] }): JSX.Element {
  return (
    <Table.Root size="compact">
      <Table.Header>
        <Table.Row>
          <Table.Head>Type</Table.Head>
          <Table.Head>Name</Table.Head>
          <Table.Head>Time</Table.Head>
          <Table.Head>Owner</Table.Head>
          <Table.Head>Approvers</Table.Head>
          <Table.Head>
            <span className="sr-only">Actions</span>
          </Table.Head>
        </Table.Row>
      </Table.Header>
      <Table.Body>
        {rows.map(row => (
          <Table.Row key={row.id}>
            <Table.Cell>
              <Text variant="body-single-line-normal" color="foreground-2">
                {row.type}
              </Text>
            </Table.Cell>
            <Table.Cell className="font-medium">{row.name}</Table.Cell>
            <Table.Cell>
              <Text variant="caption-single-line-normal" color="foreground-3">
                {row.time}
              </Text>
            </Table.Cell>
            <Table.Cell>
              <PrincipalCell principals={row.owners} />
            </Table.Cell>
            <Table.Cell>
              {row.approvers && row.approvers.length > 0 ? (
                <PrincipalCell principals={row.approvers} />
              ) : (
                <Text variant="caption-single-line-normal" color="foreground-4">
                  Anyone with access
                </Text>
              )}
            </Table.Cell>
            <Table.Cell className="text-right">
              <Button variant="outline" size="xs" asChild>
                <Link to={`/fme/requests/${row.id}`} noHoverUnderline>
                  View
                </Link>
              </Button>
            </Table.Cell>
          </Table.Row>
        ))}
      </Table.Body>
    </Table.Root>
  )
}

function LookupCard({
  title,
  description,
  actionLabel,
  actionIcon,
  to
}: {
  title: string
  description: string
  actionLabel: string
  actionIcon: 'search-window' | 'key-back'
  to: string
}): JSX.Element {
  return (
    <Card.Root size="md" interactive={false} className="flex-1">
      <Card.Content>
        <Layout.Vertical gap="sm">
          <Text variant="heading-small" as="h2" color="foreground-1">
            {title}
          </Text>
          <Text variant="body-normal" color="foreground-3">
            {description}
          </Text>
          <Button variant="outline" size="md" asChild className="mt-cn-xs w-full">
            <Link to={to} noHoverUnderline>
              <IconV2 name={actionIcon} />
              {actionLabel}
            </Link>
          </Button>
        </Layout.Vertical>
      </Card.Content>
    </Card.Root>
  )
}

function OverviewPage(): JSX.Element {
  return (
    <SandboxLayout.Main>
      <SandboxLayout.Content className="py-cn-xl">
        <Layout.Vertical gap="xl">
          {/* Location chrome — breadcrumb + page-level view toggles */}
          <Layout.Horizontal gap="sm" align="center">
            <Button variant="ghost" size="sm" iconOnly tooltipProps={{ content: 'Toggle AI chat' }}>
              <IconV2 name="chat-bubble" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              iconOnly
              tooltipProps={{ content: 'Toggle panel' }}
            >
              <IconV2 name="expand-sidebar" />
            </Button>
            <Breadcrumb.Root>
              <Breadcrumb.List>
                <Breadcrumb.Item>
                  <Breadcrumb.Link href="/fme">Feature Rollout</Breadcrumb.Link>
                </Breadcrumb.Item>
                <Breadcrumb.Separator />
                <Breadcrumb.Item>
                  <Breadcrumb.Link href="/fme/project">my-project</Breadcrumb.Link>
                </Breadcrumb.Item>
                <Breadcrumb.Separator />
                <Breadcrumb.Item>
                  <Breadcrumb.Link href="/fme/project/env">production</Breadcrumb.Link>
                </Breadcrumb.Item>
                <Breadcrumb.Separator />
                <Breadcrumb.Item>
                  <Breadcrumb.Page>Overview</Breadcrumb.Page>
                </Breadcrumb.Item>
              </Breadcrumb.List>
            </Breadcrumb.Root>
          </Layout.Horizontal>

          <Text variant="heading-section" as="h1" color="foreground-1">
            Overview
          </Text>

          {/* Two quick-action lookups, equal weight, side by side */}
          <Layout.Horizontal gap="md" align="stretch">
            <LookupCard
              title="Jump to a flag or segment"
              description="Quickest way to find and edit your active features."
              actionLabel="Find flags or segments"
              actionIcon="search-window"
              to="/fme/search"
            />
            <LookupCard
              title="Key lookup"
              description="Evaluate a key for feature flag treatments and segment membership."
              actionLabel="Evaluate key"
              actionIcon="key-back"
              to="/fme/evaluate"
            />
          </Layout.Horizontal>

          {/* Work queues — each section expands in place; many can be open */}
          <Accordion.Root
            type="multiple"
            indicatorPosition="left"
            defaultValue={['approvals', 'submissions', 'metrics']}
          >
            <Accordion.Item value="approvals">
              <Accordion.Trigger>
                <Text variant="heading-small" as="span" color="foreground-1">
                  Outstanding approvals
                </Text>
              </Accordion.Trigger>
              <Accordion.Content>
                <ApprovalsTable rows={outstandingApprovals} />
              </Accordion.Content>
            </Accordion.Item>

            <Accordion.Item value="submissions">
              <Accordion.Trigger>
                <Text variant="heading-small" as="span" color="foreground-1">
                  Outstanding submissions
                </Text>
              </Accordion.Trigger>
              <Accordion.Content>
                <SubmissionsTable rows={outstandingSubmissions} />
              </Accordion.Content>
            </Accordion.Item>

            <Accordion.Item value="metrics">
              <Accordion.Trigger>
                <Text variant="heading-small" as="span" color="foreground-1">
                  Feature flags with metrics impact for review: 0
                </Text>
              </Accordion.Trigger>
              <Accordion.Content>
                <Table.Root size="compact">
                  <Table.Header>
                    <Table.Row>
                      <Table.Head>Type</Table.Head>
                      <Table.Head>Name</Table.Head>
                      <Table.Head>Time</Table.Head>
                      <Table.Head>Owner</Table.Head>
                      <Table.Head>Approvers</Table.Head>
                    </Table.Row>
                  </Table.Header>
                  <Table.Body>
                    <Table.Row>
                      <Table.Cell colSpan={5} className="text-center">
                        <Layout.Horizontal gap="2xs" justify="center" align="center">
                          <Text variant="body-normal" color="foreground-3">
                            No feature flags to review.
                          </Text>
                          <Link to="/fme/experiments" size="sm">
                            See Experiments
                          </Link>
                        </Layout.Horizontal>
                      </Table.Cell>
                    </Table.Row>
                  </Table.Body>
                </Table.Root>
              </Accordion.Content>
            </Accordion.Item>
          </Accordion.Root>
        </Layout.Vertical>
      </SandboxLayout.Content>
    </SandboxLayout.Main>
  )
}

/* ────────────────────────────────────────────────────────────────────────
 * Shell — three-zone grid: 256px nav · 412px chat · 1fr main
 * ──────────────────────────────────────────────────────────────────────── */

export default function FmeOverviewPrototype(): JSX.Element {
  return (
    <Sidebar.Provider>
      <Layout.Grid
        columns="var(--cn-sidebar-container-full-width) auto 1fr"
        className="cn-content-full-height w-full bg-cn-2"
      >
        <AppNav />
        <ChatPanel />
        <div className="overflow-y-auto">
          <OverviewPage />
        </div>
      </Layout.Grid>
    </Sidebar.Provider>
  )
}
