import { useMemo, useState } from 'react'

import {
  Alert,
  Button,
  Card,
  IconV2,
  Layout,
  Select,
  Sidebar,
  SidebarLayout,
  Slider,
  Text
} from '@harnessio/ui/components'
import { SandboxLayout } from '@harnessio/views'

/**
 * Product Manager Dashboard — FME (Feature Management & Experimentation).
 *
 * Prototype generated by designAI's /design-prototype from the Figma frame
 * "Developer Dashboard" (node 248:2313, the Split-style PM dashboard), rebuilt
 * in the Harness Canary visual language and dropped into the real app shell
 * (left nav + main content, chat zone collapsed) per the attached reference.
 *
 * Primary intent: the "Impression Distribution over time" panel is INTERACTIVE.
 * The slider scrubs a 12-month timeline; the donut, its legend percentages, and
 * the center date all update to the scrubbed month (→ honest status — the chart
 * reflects the selected point in time, never a hopeful default).
 *
 * System honesty note: @harnessio/ui ships NO chart component (verified against
 * the 160-component manifest — `Chart` does not exist, and `Legend` is a form
 * fieldset legend). The donut, sparklines, and trend line are therefore custom
 * SVG — the one off-system surface here. They're driven by the real
 * `--cn-comp-data-viz-*` tokens (01-blue / 02-purple / 05-indigo / 07-cyan) so
 * color still re-themes and survives light/dark, and every series is paired with
 * a text label + value (→ color is never the only signal). Everything else is a
 * real @harnessio/ui component and verifies clean against the manifest.
 */

// ─── Data ────────────────────────────────────────────────────────────────────

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

type Treatment = {
  key: string
  label: string
  /** cn data-viz token name driving this series' color */
  colorVar: string
}

const TREATMENTS: Treatment[] = [
  { key: 'a', label: 'Treatment A', colorVar: '--cn-comp-data-viz-01-blue' },
  { key: 'b', label: 'Treatment B', colorVar: '--cn-comp-data-viz-05-indigo' },
  { key: 'c', label: 'Treatment C', colorVar: '--cn-comp-data-viz-02-purple' },
  { key: 'd', label: 'Treatment D', colorVar: '--cn-comp-data-viz-07-cyan' }
]

/**
 * Impression share per treatment across the 12 months — a believable rollout
 * ramp: Treatment A is dialed up over the year while D is wound down. Rows are
 * raw impression counts (thousands); percentages are derived per month so the
 * donut is always honest about the selected point in time.
 */
const IMPRESSIONS_BY_MONTH: number[][] = [
  // [A, B, C, D]
  [120, 110, 95, 130],
  [150, 112, 92, 118],
  [190, 120, 90, 100],
  [240, 122, 86, 84],
  [300, 130, 80, 70],
  [360, 128, 74, 58],
  [430, 132, 70, 46],
  [500, 130, 64, 38],
  [560, 126, 60, 30],
  [610, 120, 55, 24],
  [660, 118, 50, 20],
  [700, 115, 48, 16]
]

type MetricCardData = {
  name: string
  delta: number
  lowImpact: string
  highImpact: string
  spark: number[]
}

const TOP_SPLITS: MetricCardData[] = [
  { name: 'Domain search', delta: -57, lowImpact: '-100.00%', highImpact: '-4.23%', spark: [42, 38, 40, 30, 26, 22, 24, 18] },
  { name: 'New subscription page', delta: 13, lowImpact: '+2.10%', highImpact: '+28.40%', spark: [10, 12, 9, 14, 16, 13, 18, 20] },
  { name: 'Renew CTA', delta: 46, lowImpact: '+11.00%', highImpact: '+61.90%', spark: [8, 14, 20, 26, 30, 38, 42, 46] },
  { name: 'New subscription', delta: 24, lowImpact: '+4.80%', highImpact: '+39.10%', spark: [14, 16, 13, 19, 22, 20, 23, 24] },
  { name: 'Export my settings', delta: -12, lowImpact: '-44.20%', highImpact: '-1.10%', spark: [20, 18, 22, 16, 14, 15, 13, 12] }
]

const TREND_SERIES: { treatment: Treatment; points: number[] }[] = [
  { treatment: TREATMENTS[0], points: [40, 52, 48, 63, 60, 72, 70, 80, 78, 86, 88, 92] },
  { treatment: TREATMENTS[1], points: [55, 50, 58, 54, 60, 57, 64, 62, 68, 66, 70, 72] },
  { treatment: TREATMENTS[2], points: [62, 60, 55, 58, 50, 53, 48, 50, 45, 47, 44, 46] },
  { treatment: TREATMENTS[3], points: [70, 66, 60, 55, 50, 44, 40, 35, 33, 28, 26, 24] }
]

const METRIC_OPTIONS = [
  { label: 'My App Conversion Rate', value: 'conversion' },
  { label: 'Checkout completion', value: 'checkout' },
  { label: 'Trial-to-paid', value: 'trial' }
]

const ENV_OPTIONS = [
  { label: 'All environments', value: 'all' },
  { label: 'Production', value: 'prod' },
  { label: 'Staging', value: 'staging' }
]

// ─── Custom SVG visuals (no system Chart component exists — flagged above) ─────

/** Interactive donut: arcs animate as the scrubbed month changes. */
function DonutChart({ values }: { values: number[] }): JSX.Element {
  const total = values.reduce((sum, v) => sum + v, 0)
  const size = 168
  const stroke = 26
  const r = (size - stroke) / 2
  const cx = size / 2
  const cy = size / 2
  const circumference = 2 * Math.PI * r

  let accumulated = 0
  const arcs = values.map((value, i) => {
    const fraction = total > 0 ? value / total : 0
    const len = fraction * circumference
    const arc = {
      key: TREATMENTS[i].key,
      colorVar: TREATMENTS[i].colorVar,
      dasharray: `${len} ${circumference - len}`,
      dashoffset: -accumulated
    }
    accumulated += len
    return arc
  })

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} role="img" aria-label="Impression distribution by treatment">
      <circle cx={cx} cy={cy} r={r} fill="none" stroke="var(--cn-bg-2)" strokeWidth={stroke} />
      {arcs.map(arc => (
        <circle
          key={arc.key}
          cx={cx}
          cy={cy}
          r={r}
          fill="none"
          stroke={`var(${arc.colorVar})`}
          strokeWidth={stroke}
          strokeDasharray={arc.dasharray}
          strokeDashoffset={arc.dashoffset}
          transform={`rotate(-90 ${cx} ${cy})`}
          style={{ transition: 'stroke-dasharray 320ms ease, stroke-dashoffset 320ms ease' }}
        />
      ))}
    </svg>
  )
}

/** Tiny trend sparkline for a metric card. */
function Sparkline({ points, colorVar }: { points: number[]; colorVar: string }): JSX.Element {
  const w = 116
  const h = 40
  const max = Math.max(...points)
  const min = Math.min(...points)
  const span = max - min || 1
  const coords = points.map((p, i) => {
    const x = (i / (points.length - 1)) * w
    const y = h - ((p - min) / span) * (h - 6) - 3
    return `${x.toFixed(1)},${y.toFixed(1)}`
  })
  return (
    <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} aria-hidden="true">
      <polyline
        points={coords.join(' ')}
        fill="none"
        stroke={`var(${colorVar})`}
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

/** Multi-series trend line for "Top 5 Splits" — representative, static. */
function TrendLineChart(): JSX.Element {
  const w = 1180
  const h = 240
  const padL = 36
  const padB = 28
  const plotW = w - padL
  const plotH = h - padB
  const yTicks = [100, 75, 50, 25, 0]

  const toPath = (points: number[]): string =>
    points
      .map((p, i) => {
        const x = padL + (i / (points.length - 1)) * plotW
        const y = ((100 - p) / 100) * plotH
        return `${i === 0 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}`
      })
      .join(' ')

  return (
    <svg width="100%" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Top 5 splits metric change over time" className="overflow-visible">
      {yTicks.map((tick, i) => {
        const y = (i / (yTicks.length - 1)) * plotH
        return (
          <g key={tick}>
            <line x1={padL} y1={y} x2={w} y2={y} stroke="var(--cn-border-3)" strokeWidth={1} />
            <text x={padL - 8} y={y + 4} textAnchor="end" fontSize={11} fill="var(--cn-text-3)">
              {tick}
            </text>
          </g>
        )
      })}
      {MONTHS.map((month, i) => {
        const x = padL + (i / (MONTHS.length - 1)) * plotW
        return (
          <text key={month} x={x} y={h - 8} textAnchor="middle" fontSize={11} fill="var(--cn-text-3)">
            {month}
          </text>
        )
      })}
      {TREND_SERIES.map(series => (
        <path
          key={series.treatment.key}
          d={toPath(series.points)}
          fill="none"
          stroke={`var(${series.treatment.colorVar})`}
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      ))}
    </svg>
  )
}

// ─── Panels ────────────────────────────────────────────────────────────────

type AlertRowData = {
  id: string
  theme: 'success' | 'warning' | 'danger' | 'info'
  split: string
}

const ALERT_ROWS: AlertRowData[] = [
  { id: 'r1', theme: 'success', split: 'upsell_on_renewal' },
  { id: 'r2', theme: 'warning', split: 'domain_search' },
  { id: 'r3', theme: 'danger', split: 'new_search' },
  { id: 'r4', theme: 'info', split: 'customer_feedback_widget' },
  { id: 'r5', theme: 'success', split: 'billing_retry_flow' }
]

function AlertRow({ row }: { row: AlertRowData }): JSX.Element {
  return (
    <Alert.Root theme={row.theme}>
      <Layout.Horizontal justify="between" align="center" gap="md" className="w-full">
        <Alert.Description>
          The split{' '}
          <Text variant="body-strong" as="span" color="brand">
            {row.split}
          </Text>{' '}
          has caused 1 alert.
        </Alert.Description>
        <Button variant="outline" size="xs">
          Review alert
        </Button>
      </Layout.Horizontal>
    </Alert.Root>
  )
}

function MyAlertsPanel(): JSX.Element {
  return (
    <Card.Root size="md" interactive={false} className="flex-1">
      <Card.Content>
        <Layout.Vertical gap="md">
          <Layout.Horizontal justify="between" align="center" gap="md">
            <Text variant="heading-small" as="h2" color="foreground-1">
              My alerts
            </Text>
            <div style={{ width: 232 }}>
              <Select
                label="Environment"
                optional
                orientation="horizontal"
                size="sm"
                options={ENV_OPTIONS}
                defaultValue="all"
                onChange={() => {}}
              />
            </div>
          </Layout.Horizontal>
          <Layout.Vertical gap="xs">
            {ALERT_ROWS.map(row => (
              <AlertRow key={row.id} row={row} />
            ))}
          </Layout.Vertical>
        </Layout.Vertical>
      </Card.Content>
    </Card.Root>
  )
}

function ImpressionDistributionPanel(): JSX.Element {
  const [monthIndex, setMonthIndex] = useState(IMPRESSIONS_BY_MONTH.length - 1)

  const current = IMPRESSIONS_BY_MONTH[monthIndex]
  const total = useMemo(() => current.reduce((sum, v) => sum + v, 0), [current])
  const month = MONTHS[monthIndex]

  return (
    <Card.Root size="md" interactive={false} style={{ width: 460 }}>
      <Card.Content>
        <Layout.Vertical gap="lg">
          <Layout.Vertical gap="xs">
            <Text variant="heading-small" as="h2" color="foreground-1">
              Impression distribution over time
            </Text>
            <div style={{ width: 240 }}>
              <Select
                label="Split"
                optional
                orientation="horizontal"
                size="sm"
                options={METRIC_OPTIONS}
                defaultValue="conversion"
                onChange={() => {}}
              />
            </div>
          </Layout.Vertical>

          {/* Donut + legend with live percentages */}
          <Layout.Horizontal gap="lg" align="center" justify="between">
            <div className="relative shrink-0">
              <DonutChart values={current} />
              <Layout.Vertical
                gap="none"
                align="center"
                justify="center"
                className="absolute inset-0 pointer-events-none"
              >
                <Text variant="caption-single-line-normal" color="foreground-3">
                  {month} 2021
                </Text>
                <Text variant="heading-subsection" as="span" color="foreground-1">
                  {total.toLocaleString()}K
                </Text>
                <Text variant="caption-single-line-normal" color="foreground-3">
                  impressions
                </Text>
              </Layout.Vertical>
            </div>

            <Layout.Vertical gap="xs" className="shrink-0">
              {TREATMENTS.map((t, i) => {
                const pct = total > 0 ? Math.round((current[i] / total) * 100) : 0
                return (
                  <Layout.Horizontal key={t.key} gap="xs" align="center">
                    <span
                      aria-hidden="true"
                      className="shrink-0 rounded-cn-1"
                      style={{ width: 10, height: 10, backgroundColor: `var(${t.colorVar})` }}
                    />
                    <Text variant="caption-single-line-normal" color="foreground-2" className="w-[88px]">
                      {t.label}
                    </Text>
                    <Text variant="caption-strong" color="foreground-1" className="w-[36px] text-right">
                      {pct}%
                    </Text>
                  </Layout.Horizontal>
                )
              })}
            </Layout.Vertical>
          </Layout.Horizontal>

          {/* The time scrubber */}
          <Layout.Vertical gap="2xs">
            <Slider
              aria-label="Scrub timeline"
              value={[monthIndex]}
              min={0}
              max={IMPRESSIONS_BY_MONTH.length - 1}
              step={1}
              caption="min-max"
              minLabel="Jan 2021"
              maxLabel="Dec 2021"
              onValueChange={([v]) => setMonthIndex(v)}
            />
            <Text variant="caption-single-line-normal" color="foreground-3" align="center">
              Drag to scrub time · showing {month} 2021
            </Text>
          </Layout.Vertical>
        </Layout.Vertical>
      </Card.Content>
    </Card.Root>
  )
}

function MetricCard({ data, selected }: { data: MetricCardData; selected?: boolean }): JSX.Element {
  const positive = data.delta >= 0
  const colorVar = positive ? '--cn-comp-data-viz-05-indigo' : '--cn-comp-data-viz-02-purple'
  return (
    <Card.Root size="sm" interactive={false} selected={selected} className="flex-1">
      <Card.Content>
        <Layout.Vertical gap="xs">
          <Text variant="caption-single-line-normal" color="foreground-2" truncate>
            {data.name}
          </Text>
          <Layout.Horizontal gap="sm" align="center" justify="between">
            <Layout.Horizontal gap="2xs" align="center">
              <IconV2 name={positive ? 'nav-arrow-up' : 'nav-arrow-down'} size="sm" />
              <Text variant="heading-section" as="span" color={positive ? 'success' : 'danger'}>
                {positive ? '+' : ''}
                {data.delta}
              </Text>
            </Layout.Horizontal>
            <Sparkline points={data.spark} colorVar={colorVar} />
          </Layout.Horizontal>
          <Layout.Vertical gap="3xs">
            <Text variant="caption-light" color="foreground-4">
              Impact lies between
            </Text>
            <Text variant="caption-single-line-normal" color="foreground-3">
              {data.lowImpact} and {data.highImpact}
            </Text>
          </Layout.Vertical>
        </Layout.Vertical>
      </Card.Content>
    </Card.Root>
  )
}

function TopSplitsPanel(): JSX.Element {
  return (
    <Card.Root size="md" interactive={false}>
      <Card.Content>
        <Layout.Vertical gap="lg">
          <Layout.Horizontal justify="between" align="start" gap="md">
            <Layout.Vertical gap="3xs">
              <Text variant="heading-small" as="h2" color="foreground-1">
                Top 5 splits — metric change over time
              </Text>
              <Text variant="caption-normal" color="foreground-3">
                How the selected metric changed over time across your top 5 splits.
              </Text>
            </Layout.Vertical>
            <div style={{ width: 240 }}>
              <Select
                label="Metric"
                optional
                orientation="horizontal"
                size="sm"
                options={METRIC_OPTIONS}
                defaultValue="conversion"
                onChange={() => {}}
              />
            </div>
          </Layout.Horizontal>

          <Layout.Horizontal gap="sm" align="stretch">
            {TOP_SPLITS.map((split, i) => (
              <MetricCard key={split.name} data={split} selected={i === 0} />
            ))}
          </Layout.Horizontal>

          <Layout.Vertical gap="sm">
            <TrendLineChart />
            <Layout.Horizontal gap="md" align="center" justify="center" wrap="wrap">
              {TREATMENTS.map(t => (
                <Layout.Horizontal key={t.key} gap="2xs" align="center">
                  <span
                    aria-hidden="true"
                    className="shrink-0 rounded-cn-1"
                    style={{ width: 10, height: 10, backgroundColor: `var(${t.colorVar})` }}
                  />
                  <Text variant="caption-single-line-normal" color="foreground-2">
                    {t.label}
                  </Text>
                </Layout.Horizontal>
              ))}
            </Layout.Horizontal>
          </Layout.Vertical>
        </Layout.Vertical>
      </Card.Content>
    </Card.Root>
  )
}

// ─── Shell ───────────────────────────────────────────────────────────────────

function AppNav(): JSX.Element {
  return (
    <Sidebar.Root className="cn-content-full-height">
      <Sidebar.Content>
        <Sidebar.Group label="FEATURE MANAGEMENT">
          <Sidebar.Item icon="dashboard-solid" title="Dashboard" active />
          <Sidebar.Item icon="feature-flags" title="Feature Flags" />
          <Sidebar.Item icon="view-grid" title="Segments" />
          <Sidebar.Item icon="gauge" title="Metrics" />
          <Sidebar.Item icon="settings-solid" title="Settings" />
        </Sidebar.Group>
      </Sidebar.Content>
    </Sidebar.Root>
  )
}

function MainContent(): JSX.Element {
  return (
    <SandboxLayout.Main>
      <SandboxLayout.Content className="py-cn-xl">
        <Layout.Vertical gap="xl">
          <Layout.Vertical gap="3xs">
            <Text variant="heading-section" as="h1" color="foreground-1">
              Product Manager Dashboard
            </Text>
            <Text variant="body-normal" color="foreground-3">
              Where should I focus first?
            </Text>
          </Layout.Vertical>

          <Layout.Horizontal gap="md" align="stretch">
            <MyAlertsPanel />
            <ImpressionDistributionPanel />
          </Layout.Horizontal>

          <Layout.Vertical gap="sm">
            <Text variant="body-normal" color="foreground-3">
              What is the status of my metrics and feature flags?
            </Text>
            <TopSplitsPanel />
          </Layout.Vertical>
        </Layout.Vertical>
      </SandboxLayout.Content>
    </SandboxLayout.Main>
  )
}

export default function PmDashboardPrototype(): JSX.Element {
  return (
    <Sidebar.Provider>
      <SidebarLayout sidebar={<AppNav />} chat={null} mainContent={<MainContent />} />
    </Sidebar.Provider>
  )
}
