import type { FlowConfig } from "@harnessio/ui/components";
import {
  ChooseProviderCard,
  GithubAuthCard,
  GheAuthCard,
  GitlabAuthCard,
  BitbucketAuthCard,
  AzureAuthCard,
  GitAuthCard,
  CreateSecretCard,
  CreateConnectorCard,
  DelegateCheckCard,
  InstallDelegateCard,
  VerifyDelegateCard,
  TestConnectionCard,
  ConnectionFailedCard,
  RepoSelectionCard,
  ChooseInfraCard,
  K8sConnectorCard,
  K8sTestCard,
  DockerSetupCard,
  VmSetupCard,
  ScanRepoCard,
  ReviewPipelineCard,
  CommitPipelineCard,
  TriggerBuildCard,
  BuildFailedCard,
  OnboardingCompleteCard,
} from "./mock-cards";

export const fullFlow: FlowConfig = {
  steps: {
    source: {
      title: "Connect Source Code",
      description: "Connect Harness to your code",
    },
    repository: {
      title: "Select Repository",
      description: "Choose which repo to build",
    },
    infrastructure: {
      title: "Configure Build Environment",
      description: "Set up where builds will run",
    },
    pipeline: {
      title: "Create Pipeline",
      description: "Generate and configure your CI pipeline",
    },
    verify: {
      title: "Verify",
      description: "Run and confirm everything works",
    },
  },
  subSteps: {
    "choose-provider": {
      step: "source",
      title: "Choose code provider",
      component: ChooseProviderCard,
      next: "github-auth",
    },
    "github-auth": {
      step: "source",
      title: "Authenticate with GitHub",
      component: GithubAuthCard,
      next: "test-connection",
    },
    "ghe-auth": {
      step: "source",
      title: "Authenticate with GitHub Enterprise",
      component: GheAuthCard,
      next: "create-secret",
    },
    "gitlab-auth": {
      step: "source",
      title: "Authenticate with GitLab",
      component: GitlabAuthCard,
      next: "create-connector",
    },
    "bitbucket-auth": {
      step: "source",
      title: "Authenticate with Bitbucket",
      component: BitbucketAuthCard,
      next: "create-connector",
    },
    "azure-auth": {
      step: "source",
      title: "Authenticate with Azure Repos",
      component: AzureAuthCard,
      next: "create-connector",
    },
    "git-auth": {
      step: "source",
      title: "Authenticate with Git",
      component: GitAuthCard,
      next: "create-secret",
    },
    "create-secret": {
      step: "source",
      title: "Store credentials",
      component: CreateSecretCard,
      next: "create-connector",
    },
    "create-connector": {
      step: "source",
      title: "Create connector",
      component: CreateConnectorCard,
      next: "test-connection",
    },
    "delegate-check": {
      step: "infrastructure",
      title: "Checking delegate availability",
      component: DelegateCheckCard,
      next: "install-delegate",
    },
    "install-delegate": {
      step: "infrastructure",
      title: "Install a Delegate",
      component: InstallDelegateCard,
      next: "verify-delegate",
    },
    "verify-delegate": {
      step: "infrastructure",
      title: "Waiting for delegate",
      component: VerifyDelegateCard,
      next: "scan-repo",
    },
    "test-connection": {
      step: "source",
      title: "Verify connection",
      component: TestConnectionCard,
      next: "repo-selection",
    },
    "connection-failed": {
      step: "source",
      title: "Connection failed",
      component: ConnectionFailedCard,
      next: "choose-provider",
    },
    "repo-selection": {
      step: "repository",
      title: "Select a repository",
      component: RepoSelectionCard,
      next: "choose-infra",
    },
    "choose-infra": {
      step: "infrastructure",
      title: "Choose build infrastructure",
      component: ChooseInfraCard,
      next: "scan-repo",
    },
    "k8s-connector": {
      step: "infrastructure",
      title: "Configure Kubernetes cluster",
      component: K8sConnectorCard,
      next: "k8s-test",
    },
    "k8s-test": {
      step: "infrastructure",
      title: "Testing cluster connection",
      component: K8sTestCard,
      next: "delegate-check",
    },
    "docker-setup": {
      step: "infrastructure",
      title: "Set up Docker runner",
      component: DockerSetupCard,
      next: "delegate-check",
    },
    "vm-setup": {
      step: "infrastructure",
      title: "Configure cloud VMs",
      component: VmSetupCard,
      next: "delegate-check",
    },
    "scan-repo": {
      step: "pipeline",
      title: "Analyzing your repository",
      component: ScanRepoCard,
      next: "review-pipeline",
    },
    "review-pipeline": {
      step: "pipeline",
      title: "Review pipeline configuration",
      component: ReviewPipelineCard,
      next: "commit-pipeline",
    },
    "commit-pipeline": {
      step: "pipeline",
      title: "Saving pipeline",
      component: CommitPipelineCard,
      next: "trigger-build",
    },
    "trigger-build": {
      step: "verify",
      title: "Running first build",
      component: TriggerBuildCard,
      next: "onboarding-complete",
    },
    "build-failed": {
      step: "verify",
      title: "Build failed",
      component: BuildFailedCard,
      next: "review-pipeline",
    },
    "onboarding-complete": {
      step: "verify",
      title: "Pipeline ready!",
      component: OnboardingCompleteCard,
    },
  },
  initialSubStep: "choose-provider",
};
