name: PR Checks
on:
  push:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm build
      - run: pnpm lint

  Prettier:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm pretty

  Typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm build
      - run: pnpm typecheck

  Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm build
      - run: pnpm test

  Build_Microfrontend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: cd apps/gitness
      - run: pnpm install
      - run: pnpm run build:webpack
