name: PR Checks
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  CheckCleanGitTree:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm build
      - name: Check for uncommitted changes
        run: |
          # Show only the names of changed files
          echo "Changed files:"
          git diff --name-only HEAD --exit-code || (echo "Error: There are uncommitted changes in the working tree. Please commit or revert these changes." && exit 1)

  Lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm build
      - run: pnpm lint

  Prettier:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm pretty

  Typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm build
      - run: pnpm typecheck

  Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm deps
      - run: pnpm build
      - run: pnpm test

  Build_Microfrontend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm build
      - run: pnpm -r -F ./apps/gitness build:webpack
