name: Publish Packages to npm

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc

      - name: Publish packages
        run: pnpm publish:all

      - name: Generate publish report
        run: pnpm ls --depth=0 | grep '└──'
