name: Publish Packages to npm

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/*/package.json'
    types:
      - opened
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Detect changed package(s)
        id: changed-packages
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main)
          for file in $CHANGED_FILES; do
            if [[ $file == packages/*/package.json ]]; then
              PACKAGE_PATH=$(dirname "$file")
              echo "Detected package change: $PACKAGE_PATH"
              echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV
              break
            fi
          done
      - name: Install dependencies
        if: env.PACKAGE_PATH != ''
        run: pnpm install
      - name: Publish package to npm
        if: env.PACKAGE_PATH != ''
        run: pnpm publish --access public --no-git-checks
        working-directory: ${{ env.PACKAGE_PATH }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
