name: Publish Packages to npm

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/*/package.json'
    types:
      - opened
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install and build dependencies
        run: |
          pnpm install
          pnpm build

      - name: Authenticate to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc

      - name: Detect changed package(s)
        id: changed-packages
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main)
          DETECTED_PACKAGES=""
          for file in $CHANGED_FILES; do
            if [[ $file == packages/*/package.json ]]; then
              PACKAGE_PATH=$(dirname "$file")
              echo "Change detected in package: $PACKAGE_PATH"
              if [[ -z "$DETECTED_PACKAGES" ]]; then
                DETECTED_PACKAGES="$PACKAGE_PATH"
              else
                DETECTED_PACKAGES="$DETECTED_PACKAGES,$PACKAGE_PATH"
              fi
            fi
          done
          echo "detected_packages=$DETECTED_PACKAGES" >> $GITHUB_ENV

      - name: Publish packages to npm
        if: env.detected_packages != ''
        run: |
          IFS=',' read -ra PACKAGES <<< "$detected_packages"
          for PACKAGE_PATH in "${PACKAGES[@]}"; do
            echo "Publishing package: $PACKAGE_PATH"
            pnpm publish --access public --filter "./$PACKAGE_PATH" --no-git-checks
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
